### ISSUE TITLE
Do initial merge of GitScripts3 and master branches

### ISSUE THREAD

**Issue by chriscorwin** [cmcculloh/GitScripts#95]
![](https://emoji.slack-edge.com/T02GNTR51/fingers-crossed/fcda452871c33244.png)

**Comment by cmcculloh** [comment]
I've merged master into GitScripts 3. The only reason to use master at this point is if for some reason you need the "admin" stuff that I ripped out of GitScripts 3.

I wouldn't be completely opposed to putting some of the admin and branchprotection stuff back in and just disabling it by default (instead of enabling). I just wasn't finding it useful AT ALL and it made the spaghetti more tangled. If we want to put it back for some reason, we can open a new issue for it.
